steps:
  - id: "Rodando docker-compose"
    name: "gcr.io/$PROJECT_ID/docker-compose"
    args: ["-f", "docker-compose.cloudbuild.yml", "up", "-d"]

  - id: "Rodando: docker ps"
    name: "gcp.io/$PROJECT_ID/docker"
    args: ["ps"]
